-- 院系B（Oracle）建表脚本（对应PDF表3-6~3-9）
-- 约定：表名前缀 B_

-- 安全删除（忽略不存在的表）
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE B_ACCOUNT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE B_CHOICE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE B_COURSE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE B_STUDENT';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 表3-7：学生表
CREATE TABLE B_STUDENT (
  SNO    VARCHAR2(9)  PRIMARY KEY,
  SNM    VARCHAR2(10) NOT NULL,
  SEX    VARCHAR2(2)  NOT NULL,
  MAJOR  VARCHAR2(16) NOT NULL,
  DEPT   VARCHAR2(6)  NOT NULL
);

-- 表3-8：课程表
CREATE TABLE B_COURSE (
  CNO      VARCHAR2(5)  PRIMARY KEY,
  CNM      VARCHAR2(16) NOT NULL,
  HOURS    VARCHAR2(2)  NOT NULL,
  CREDIT   VARCHAR2(1)  NOT NULL,
  TEACHER  VARCHAR2(10) NOT NULL,
  LOCATION VARCHAR2(20) NOT NULL,
  ATTR     CHAR(1)      NOT NULL
);

-- 表3-9：选课表（PDF中主键描述不够精确，这里采用(学号,课程号)复合主键以支持多对多）
CREATE TABLE B_CHOICE (
  SNO   VARCHAR2(9) NOT NULL,
  CNO   VARCHAR2(5) NOT NULL,
  SCORE VARCHAR2(3),
  CONSTRAINT PK_B_CHOICE PRIMARY KEY (SNO, CNO),
  CONSTRAINT FK_B_CHOICE_STU FOREIGN KEY (SNO) REFERENCES B_STUDENT(SNO),
  CONSTRAINT FK_B_CHOICE_CRS FOREIGN KEY (CNO) REFERENCES B_COURSE(CNO)
);

-- 表3-6：账户表
CREATE TABLE B_ACCOUNT (
  ACC    VARCHAR2(12) PRIMARY KEY,
  PASSWD VARCHAR2(12) NOT NULL,
  ROLE   NUMBER(2)    NOT NULL,
  SNO    VARCHAR2(9),
  CONSTRAINT FK_B_ACC_STU FOREIGN KEY (SNO) REFERENCES B_STUDENT(SNO)
);

CREATE INDEX IDX_B_ACC_SNO ON B_ACCOUNT(SNO);
CREATE INDEX IDX_B_CHOICE_CNO ON B_CHOICE(CNO);
